- hosts: anb-ansible-client
  remote_user: root

  tasks:
  - name: ensure postgresql is at the latest version
    yum:
      name: postgresql
      state: latest
    yum:
      name: wget
      state: latest
  - name: ensure that postgresql is started
    service:
      name: postgresql
      state: started

